export enum AuthActionsTypes {
	SIGN_IN = 'SIGN_IN',
	SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE = 'SIGN_IN_FAILURE',
	SIGN_OUT = 'SIGN_OUT',
	SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS',
	SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE',
	ON_AUTH_STATE_CHANGED = 'ON_AUTH_STATE_CHANGED',
}
